### ISSUE TITLE
Incorrect triangle geometry index type

### ISSUE THREAD

**Issue by jeffamstutz** [ospray/anari-ospray#8]
`triangle` geometry should accept `ANARI_UINT32_VEC3` indicies, but requires OSPRay's `mesh` geometry indexing with `VEC4`.

Error message with valid geometry:
```
[ERROR][(nil)] ospray::Mesh must have 'index' 1D array with element type vec4ui
```

**Comment by tarkpate** [comment]
Hi, the Ospray Mesh supports both vec3ui(tri mesh) and vec4ui(quad mesh) which map to the Anari vector types. The example "instanced_cubes" uses triangle meshes. The error message when neither were present failed to mention vec3ui. I've opened a [PR on the Ospray repo](https://github.com/ospray/ospray/pull/561) to address this.
